# Generated by Django 4.2.7 on 2024-01-10 09:43

from django.db import migrations, models
import site_admin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thumbnails',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='media/static/thumbnails/', validators=[site_admin.models.validate_image_extension])),
            ],
        ),
    ]
